/* eslint-disable @next/next/no-img-element */
import { Container, Eyebrow } from "@/components/ui/layout";
import { Reveal } from "@/components/ui/Reveal";

type Mark = { src: string; name: string };
type Lane = { title: string; tag: string; body: string; proof: string; marks: Mark[] };

const LANES: Lane[] = [
  {
    title: "Excel, Word, PowerPoint, PDF",
    tag: "Open in Tenure",
    body: "Contracts, decks, and spreadsheets open in the app, PowerPoint with its speaker notes. Spreadsheets and text files can be edited in place and versioned, and Tenure tells you if someone else saved first.",
    proof: "xlsx · docx · pptx · pdf",
    marks: [{ src: "/logos/tools/excel.svg", name: "Excel" }],
  },
  {
    title: "Outlook, Google, Apple Calendar",
    tag: "Subscribe, one link",
    body: "Subscribe to the Tenure calendar from the one you already open. No account connection and no password shared: the link is signed to you, so it carries only what your seat is allowed to see. One-way today, Tenure fills your calendar and does not read it back.",
    proof: "signed feed · one-way today",
    marks: [
      { src: "/logos/tools/outlook.svg", name: "Outlook" },
      { src: "/logos/tools/google-calendar.svg", name: "Google Calendar" },
    ],
  },
  {
    title: "Your existing budget spreadsheet",
    tag: "Imported, columns matched",
    body: "Upload the budget you already keep. Tenure works out which column is which, whatever you named them, drops your subtotal rows so nothing double-counts, and shows you what it read before anything is saved. Or start from our template, generated by the same code that reads it.",
    proof: "columns auto-matched · preview before save",
    marks: [{ src: "/logos/tools/excel.svg", name: "Excel" }],
  },
];

function Chip({ t }: { t: Mark }) {
  return (
    <span className="inline-flex items-center gap-2 rounded-lg border border-line bg-paper/60 px-2.5 py-1.5">
      <img src={t.src} alt="" width={18} height={18} className="h-[18px] w-[18px] object-contain" loading="lazy" />
      <span className="whitespace-nowrap text-[0.78rem] font-medium text-ink-soft">{t.name}</span>
    </span>
  );
}

export function Integrations() {
  return (
    <section className="relative overflow-hidden border-t border-line bg-paper py-24 sm:py-28">
      <Container>
        <div className="mx-auto max-w-2xl text-center">
          <Reveal>
            <Eyebrow className="justify-center">Fits your stack</Eyebrow>
          </Reveal>
          <Reveal delay={0.06}>
            <h2 className="font-display mt-5 text-[2rem] font-semibold leading-[1.08] tracking-[-0.03em] text-ink sm:text-[2.5rem]">
              Bring what you already have. Keep{" "}
              <span className="text-gradient">the calendar you already open</span>.
            </h2>
          </Reveal>
          <Reveal delay={0.12}>
            <p className="mx-auto mt-5 max-w-xl text-lg leading-relaxed text-ink-soft">
              Upload the budget spreadsheet and Tenure reads your columns however you
              named them. Drop in the decks, contracts, and PDFs and they open in-app.
              Subscribe your Outlook, Google, or Apple Calendar with one signed link,
              no password shared.
            </p>
          </Reveal>
        </div>

        <div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {LANES.map((l, i) => (
            <Reveal as="div" key={l.title} delay={0.05 * i}>
              <div className="lift flex h-full flex-col rounded-2xl border border-line bg-cloud p-6 shadow-[0_1px_2px_rgba(12,30,51,0.05)] hover:-translate-y-1 hover:border-grove/25 hover:shadow-[0_24px_54px_-30px_rgba(12,30,51,0.4)]">
                <div className="flex flex-wrap items-center gap-2">
                  {l.marks.map((m) => (
                    <Chip key={`${l.title}-${m.name}`} t={m} />
                  ))}
                </div>
                <span className="label-mono mt-5 block">{l.tag}</span>
                <h3 className="mt-2 font-display text-[1.12rem] font-semibold leading-snug text-ink">
                  {l.title}
                </h3>
                <p className="mt-2.5 text-[0.95rem] leading-relaxed text-ink-soft">{l.body}</p>
                <p className="mt-auto pt-5 font-mono text-[0.62rem] text-ink-faint">{l.proof}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </Container>
    </section>
  );
}
